parameters: {}
environment: {}
packages:
    - name: spaces
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: index
          binary: false
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
